### ISSUE TITLE
QXcbConnection: Could not connect to display 

### ISSUE THREAD

**Issue by RobSap** [fadawar/docker-pyqt5#1]
When I clone, build, then run I get the following error: QXcbConnection: Could not connect to display 
I've searched around and there are various fixes that people suggest and none work. Did you ever have this issue and is there any suggestions? 

Update: Does not work on Mac. However, works fine on a PC Virtual box Image of Ubuntu for the versions listed.

**Comment by fadawar** [comment]
I had never this kind of issue. What command exactly did you use to start container?

You can try to clone this repo and run the command from the README file. See if that is working.
